name: smart_media_picker_and_viewer
description: "A versatile Flutter package for picking and viewing various media types."
version: 0.0.6
homepage: https://github.com/hs-dev1/smart_media_picker_and_viewer
repository: https://github.com/hs-dev1/smart_media_picker_and_viewer



environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  open_file: ^3.3.2
  dotted_border: ^2.1.0
  carousel_slider: ^5.0.0
  flutter_pdfview: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0


flutter:

# This package supports only Android and IOS.
platforms:
  android:
  ios:

topics:
  - image-picker
  - file-picker
  - view-files